name:                text-editor
version:             0.1.0.0
github:              "deh4er/text-editor"
license:             BSD3
author:              "Denys Lytviak"
maintainer:          "deh4er@gmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deh4er/text-editor#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  text-editor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-editor

tests:
  text-editor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-editor
