name: text-editor
version: 0.1.0.0
author: Denys Lytviak
github: deh4er/text-editor
license: BSD3
copyright: BSD
maintainer: deh4er@gmail.com
description: Please see the README on GitHub at <https://github.com/deh4er/text-editor#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- vty
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

tests:
  text-editor-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-editor
    - hspec

executables:
  text-editor-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-editor
    - vty == 5.26
